services:
  server:
    build:
      context: ./Back-End
    ports:
      - "8080:8080"

  client_web:
    build:
      context: ./Front-End/Web
    ports:
      - "8081:8081"
    depends_on:
      - server

  # client_mobile:
  #   build:
  #     context: ./Front-End/Mobile
